### ISSUE TITLE
shylock-bot Git Repo

### ISSUE THREAD

**Issue by francesharlow** [notzooey/shylock-bot#1]
Hey Anna,

I created a project folder, initialized a new Git repository, and linked it to the corresponding Github remote origin. Then I added you, Sung, and Phil as collaborators. Everything seems to be working correctly -- just let me know if I'm missing something, or my invitation to collaborate was unsuccessful.

Thanks!

**Comment by annarankin** [comment]
Hey Frances, looking good! :+1:
